// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDucYdHTuE6Niou_WleFaW5VYpbUOwEwBM',
    appId: '1:162226382701:web:c4485e6574db6daf919c64',
    messagingSenderId: '162226382701',
    projectId: 'nalar-d1fb0',
    authDomain: 'nalar-d1fb0.firebaseapp.com',
    storageBucket: 'nalar-d1fb0.firebasestorage.app',
    measurementId: 'G-4TBVJ374CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoO6uUTpeDF8ZNrK4aUxp_6QFWUl0ng38',
    appId: '1:162226382701:android:1d245d8189bab212919c64',
    messagingSenderId: '162226382701',
    projectId: 'nalar-d1fb0',
    storageBucket: 'nalar-d1fb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWy_bNJQD5m4K7vzQ2d-zRMolBzSxyBg',
    appId: '1:162226382701:ios:5bae75c1e1b091d7919c64',
    messagingSenderId: '162226382701',
    projectId: 'nalar-d1fb0',
    storageBucket: 'nalar-d1fb0.firebasestorage.app',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWy_bNJQD5m4K7vzQ2d-zRMolBzSxyBg',
    appId: '1:162226382701:ios:5bae75c1e1b091d7919c64',
    messagingSenderId: '162226382701',
    projectId: 'nalar-d1fb0',
    storageBucket: 'nalar-d1fb0.firebasestorage.app',
    iosBundleId: 'com.example.ourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDucYdHTuE6Niou_WleFaW5VYpbUOwEwBM',
    appId: '1:162226382701:web:a39be2cc72a4ef31919c64',
    messagingSenderId: '162226382701',
    projectId: 'nalar-d1fb0',
    authDomain: 'nalar-d1fb0.firebaseapp.com',
    storageBucket: 'nalar-d1fb0.firebasestorage.app',
    measurementId: 'G-2053HD500E',
  );
}
